package ui;

import .*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MUHAMMAD SHAHZEB
 */
public class communicateteacher extends javax.swing.JFrame {

    /**
     * Creates new form communicate teacher
     */
    public communicateteacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepael = new javax.swing.JPanel();
        CApanel = new javax.swing.JPanel();
        CAbutton = new javax.swing.JButton();
        CApanel1 = new javax.swing.JPanel();
        CAbutton1 = new javax.swing.JButton();
        CApanel2 = new javax.swing.JPanel();
        CAbutton2 = new javax.swing.JButton();
        CApanel3 = new javax.swing.JPanel();
        CAbutton3 = new javax.swing.JButton();
        panelhome = new javax.swing.JPanel();
        buttonhome = new javax.swing.JButton();
        mapanel = new javax.swing.JPanel();
        mabutton = new javax.swing.JButton();
        SSpanel = new javax.swing.JPanel();
        SSbutton = new javax.swing.JButton();
        Ccpanel = new javax.swing.JPanel();
        CCbutton = new javax.swing.JButton();
        logoutpanel = new javax.swing.JPanel();
        logoutbutton = new javax.swing.JButton();
        rightpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        logoutpanel1 = new javax.swing.JPanel();
        logoutbutton1 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepael.setBackground(new java.awt.Color(0, 102, 102));
        sidepael.setRequestFocusEnabled(false);
        sidepael.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CApanel.setBackground(new java.awt.Color(0, 102, 102));
        CApanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        CApanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CAbutton.setBackground(new java.awt.Color(0, 101, 101));
        CAbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CAbutton.setForeground(new java.awt.Color(255, 255, 255));
        CAbutton.setText("Check Attendance");
        CAbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAbuttonActionPerformed(evt);
            }
        });
        CApanel.add(CAbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        CApanel1.setBackground(new java.awt.Color(0, 102, 102));
        CApanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        CApanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CAbutton1.setBackground(new java.awt.Color(0, 101, 101));
        CAbutton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CAbutton1.setForeground(new java.awt.Color(255, 255, 255));
        CAbutton1.setText("Check Attendance");
        CAbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAbutton1ActionPerformed(evt);
            }
        });
        CApanel1.add(CAbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        CApanel.add(CApanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 280, 50));

        CApanel2.setBackground(new java.awt.Color(0, 102, 102));
        CApanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        CApanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CAbutton2.setBackground(new java.awt.Color(0, 101, 101));
        CAbutton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CAbutton2.setForeground(new java.awt.Color(255, 255, 255));
        CAbutton2.setText("Check Attendance");
        CAbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAbutton2ActionPerformed(evt);
            }
        });
        CApanel2.add(CAbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        CApanel3.setBackground(new java.awt.Color(0, 102, 102));
        CApanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        CApanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CAbutton3.setBackground(new java.awt.Color(0, 101, 101));
        CAbutton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CAbutton3.setForeground(new java.awt.Color(255, 255, 255));
        CAbutton3.setText("Check Attendance");
        CAbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAbutton3ActionPerformed(evt);
            }
        });
        CApanel3.add(CAbutton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        CApanel2.add(CApanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 280, 50));

        CApanel.add(CApanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 280, 50));

        sidepael.add(CApanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, 50));

        panelhome.setBackground(new java.awt.Color(0, 102, 102));
        panelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonhome.setBackground(new java.awt.Color(0, 101, 101));
        buttonhome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonhome.setForeground(new java.awt.Color(255, 255, 255));
        buttonhome.setText("Home");
        buttonhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhomeActionPerformed(evt);
            }
        });
        panelhome.add(buttonhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        sidepael.add(panelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 50));

        mapanel.setBackground(new java.awt.Color(0, 102, 102));
        mapanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        mapanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mabutton.setBackground(new java.awt.Color(0, 101, 101));
        mabutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mabutton.setForeground(new java.awt.Color(255, 255, 255));
        mabutton.setText("Mark Attendance");
        mabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mabuttonActionPerformed(evt);
            }
        });
        mapanel.add(mabutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        sidepael.add(mapanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 50));

        SSpanel.setBackground(new java.awt.Color(0, 102, 102));
        SSpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        SSpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SSbutton.setBackground(new java.awt.Color(0, 101, 101));
        SSbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SSbutton.setForeground(new java.awt.Color(255, 255, 255));
        SSbutton.setText("Search Student");
        SSbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSbuttonActionPerformed(evt);
            }
        });
        SSpanel.add(SSbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        sidepael.add(SSpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 50));

        Ccpanel.setBackground(new java.awt.Color(0, 102, 102));
        Ccpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Ccpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CCbutton.setBackground(new java.awt.Color(0, 101, 101));
        CCbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CCbutton.setForeground(new java.awt.Color(255, 255, 255));
        CCbutton.setText("Check Class");
        CCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCbuttonActionPerformed(evt);
            }
        });
        Ccpanel.add(CCbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        sidepael.add(Ccpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 210, 50));

        logoutpanel.setBackground(new java.awt.Color(0, 102, 102));
        logoutpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        logoutpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbutton.setBackground(new java.awt.Color(0, 101, 101));
        logoutbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logoutbutton.setForeground(new java.awt.Color(255, 255, 255));
        logoutbutton.setText("Logout");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        logoutpanel.add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        sidepael.add(logoutpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 210, 50));

        getContentPane().add(sidepael, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 660));

        rightpanel.setBackground(new java.awt.Color(0, 153, 153));
        rightpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Teacher  Name");
        rightpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Select Class");
        rightpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 100, 80, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSE 1A", "BCS 1A", "PHR 1A", "EEE 1A", "BSE 2A", "BCS 2A", "PHR 2A", "EEE 2A", "BSE 3A", "BCS 3A", "PHR 3A", "EEE 3A", "BSE 4A", "BCS 4A", "PHR 4A", "EEE 4A", "BSE 5A", "BCS 5A", "PHR 5A", "EEE 5A", "BSE 6A", "BCS 6A", "PHR 6A", "EEE 6A", "BSE 7A", "BCS 7A", "PHR 7A", "EEE 7A", "BSE 8A", "BCS 8A", "PHR 8A", "EEE 8A", "BSE 1B", "BCS 1B", "PHR 1B", "EEE 1B", "BSE 2B", "BCS 2B", "PHR 2B", "EEE 2B", "BSE 3B", "BCS 3B", "PHR 3B", "EEE 3B", "BSE 4B", "BCS 4B", "PHR 4B", "EEE 4B", "BSE 5B", "BCS 5B", "PHR 5B", "EEE 5B", "BSE 6B", "BCS 6B", "PHR 6B", "EEE 6B", "BSE 7B", "BCS 7B", "PHR 7B", "EEE 7B", "BSE 8B", "BCS 8B", "PHR 8B", "EEE 8B", "BSE 1C", "BCS 1C", "PHR 1C", "EEE 1C", "BSE 2C", "BCS 2C", "PHR 2C", "EEE 2C", "BSE 3C", "BCS 3C", "PHR 3C", "EEE 3C", "BSE 4C", "BCS 4C", "PHR 4C", "EEE 4C", "BSE 5C", "BCS 5C", "PHR 5C", "EEE 5C", "BSE 6C", "BCS 6C", "PHR 6C", "EEE 6C", "BSE 7C", "BCS 7C", "PHR 7C", "EEE 7C", "BSE 8C", "BCS 8C", "PHR 8C", "EEE 8C", "BSE 1D", "BCS 1D", "PHR 1D", "EEE 1D", "BSE 2D", "BCS 2D", "PHR 2D", "EEE 2D", "BSE 3D", "BCS 3D", "PHR 3D", "EEE 3D", "BSE 4D", "BCS 4D", "PHR 4D", "EEE 4D", "BSE 5D", "BCS 5D", "PHR 5D", "EEE 5D", "BSE 6D", "BCS 6D", "PHR 6D", "EEE 6D", "BSE 7D", "BCS 7D", "PHR 7D", "EEE 7D", "BSE 8D", "BCS 8D", "PHR 8D", "EEE 8D" }));
        rightpanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 250, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        rightpanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 250, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Student ID");
        rightpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        rightpanel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 250, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Reason");
        rightpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 80, -1));

        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        rightpanel.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 302, 550, 250));

        logoutpanel1.setBackground(new java.awt.Color(0, 153, 153));
        logoutpanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        logoutpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbutton1.setBackground(new java.awt.Color(0, 152, 152));
        logoutbutton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logoutbutton1.setForeground(new java.awt.Color(255, 255, 255));
        logoutbutton1.setText("Send");
        logoutbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbutton1ActionPerformed(evt);
            }
        });
        logoutpanel1.add(logoutbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        rightpanel.add(logoutpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 210, 50));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        rightpanel.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 250, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Name");
        rightpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, -1));

        getContentPane().add(rightpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 640, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CAbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAbuttonActionPerformed

    private void CAbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAbutton1ActionPerformed

    private void CAbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAbutton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAbutton2ActionPerformed

    private void CAbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAbutton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAbutton3ActionPerformed

    private void buttonhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhomeActionPerformed
        // TODO add your handling code here:
        Pdashboard d = new Pdashboard();
        d.show();
        dispose();
    }//GEN-LAST:event_buttonhomeActionPerformed

    private void mabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mabuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mabuttonActionPerformed

    private void SSbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSbuttonActionPerformed

    private void CCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void logoutbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbutton1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(communicateteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(communicateteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(communicateteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(communicateteacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new communicateteacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CAbutton;
    private javax.swing.JButton CAbutton1;
    private javax.swing.JButton CAbutton2;
    private javax.swing.JButton CAbutton3;
    private javax.swing.JPanel CApanel;
    private javax.swing.JPanel CApanel1;
    private javax.swing.JPanel CApanel2;
    private javax.swing.JPanel CApanel3;
    private javax.swing.JButton CCbutton;
    private javax.swing.JPanel Ccpanel;
    private javax.swing.JButton SSbutton;
    private javax.swing.JPanel SSpanel;
    private javax.swing.JButton buttonhome;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton logoutbutton1;
    private javax.swing.JPanel logoutpanel;
    private javax.swing.JPanel logoutpanel1;
    private javax.swing.JButton mabutton;
    private javax.swing.JPanel mapanel;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel rightpanel;
    private javax.swing.JPanel sidepael;
    // End of variables declaration//GEN-END:variables
}
