/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author COMPUTER CORNER
 */
public class adashboard extends javax.swing.JFrame {

    /**
     * Creates new form adashboard
     */
    public adashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gdrbutton = new javax.swing.JButton();
        VAbutton1 = new javax.swing.JButton();
        msbutton1 = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        nbutton2 = new javax.swing.JButton();
        epbutton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gdrbutton.setBackground(new java.awt.Color(0, 153, 153));
        gdrbutton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        gdrbutton.setForeground(new java.awt.Color(255, 255, 255));
        gdrbutton.setText("Generate Discipline Report");
        jPanel1.add(gdrbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 210, -1));

        VAbutton1.setBackground(new java.awt.Color(0, 153, 153));
        VAbutton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        VAbutton1.setForeground(new java.awt.Color(255, 255, 255));
        VAbutton1.setText("View Attendance");
        jPanel1.add(VAbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, -1));

        msbutton1.setBackground(new java.awt.Color(0, 153, 153));
        msbutton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        msbutton1.setForeground(new java.awt.Color(255, 255, 255));
        msbutton1.setText("Manage Settings");
        jPanel1.add(msbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, -1));

        logoutbutton.setBackground(new java.awt.Color(0, 153, 153));
        logoutbutton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        logoutbutton.setForeground(new java.awt.Color(255, 255, 255));
        logoutbutton.setText("Logout");
        jPanel1.add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 140, -1));

        nbutton2.setBackground(new java.awt.Color(0, 153, 153));
        nbutton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        nbutton2.setForeground(new java.awt.Color(255, 255, 255));
        nbutton2.setText("Notify");
        jPanel1.add(nbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, -1));

        epbutton1.setBackground(new java.awt.Color(0, 153, 153));
        epbutton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        epbutton1.setForeground(new java.awt.Color(255, 255, 255));
        epbutton1.setText("Edit Profile");
        jPanel1.add(epbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VAbutton1;
    private javax.swing.JButton epbutton1;
    private javax.swing.JButton gdrbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton msbutton1;
    private javax.swing.JButton nbutton2;
    // End of variables declaration//GEN-END:variables
}
