/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author COMPUTER CORNER
 */
public class communicateteacher extends javax.swing.JPanel {

    /**
     * Creates new form communicateteacher
     */
    public communicateteacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        msg = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tname1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        send = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msg.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        msg.setText("Message");
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 670, 320));

        tname1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        tname1.setText("Teacher Name");
        jPanel1.add(tname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 53, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 300, 30));

        send.setBackground(new java.awt.Color(0, 153, 153));
        send.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        send.setForeground(new java.awt.Color(255, 255, 255));
        send.setText("Send");
        jPanel1.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 550));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel msg;
    private javax.swing.JButton send;
    private javax.swing.JLabel tname1;
    // End of variables declaration//GEN-END:variables
}
