/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author COMPUTER CORNER
 */

public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        Eppanel = new javax.swing.JPanel();
        Epbutton = new javax.swing.JButton();
        MApanel1 = new javax.swing.JPanel();
        MAbutton = new javax.swing.JButton();
        CApanel1 = new javax.swing.JPanel();
        CAbutton1 = new javax.swing.JButton();
        SSpanel1 = new javax.swing.JPanel();
        SSbutton1 = new javax.swing.JButton();
        CCpanel1 = new javax.swing.JPanel();
        CCbutton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpanel.setBackground(new java.awt.Color(0, 102, 102));
        mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eppanel.setBackground(new java.awt.Color(0, 102, 102));
        Eppanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eppanel.setForeground(new java.awt.Color(255, 255, 255));
        Eppanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Epbutton.setBackground(new java.awt.Color(0, 102, 102));
        Epbutton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Epbutton.setForeground(new java.awt.Color(255, 255, 255));
        Epbutton.setText("Edit Profile");
        Epbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EpbuttonActionPerformed(evt);
            }
        });
        Eppanel.add(Epbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 40));

        mainpanel.add(Eppanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 190, 100));

        MApanel1.setBackground(new java.awt.Color(0, 102, 102));
        MApanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MApanel1.setForeground(new java.awt.Color(255, 255, 255));
        MApanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MAbutton.setBackground(new java.awt.Color(0, 102, 102));
        MAbutton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MAbutton.setForeground(new java.awt.Color(255, 255, 255));
        MAbutton.setText("Mark Attendance");
        MAbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAbuttonActionPerformed(evt);
            }
        });
        MApanel1.add(MAbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 40));

        mainpanel.add(MApanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 180, 100));

        CApanel1.setBackground(new java.awt.Color(0, 102, 102));
        CApanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CApanel1.setForeground(new java.awt.Color(255, 255, 255));
        CApanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CAbutton1.setBackground(new java.awt.Color(0, 102, 102));
        CAbutton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        CAbutton1.setForeground(new java.awt.Color(255, 255, 255));
        CAbutton1.setText("Check Attendance");
        CApanel1.add(CAbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 40));

        mainpanel.add(CApanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 190, 100));

        SSpanel1.setBackground(new java.awt.Color(0, 102, 102));
        SSpanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SSpanel1.setForeground(new java.awt.Color(255, 255, 255));
        SSpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SSbutton1.setBackground(new java.awt.Color(0, 102, 102));
        SSbutton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        SSbutton1.setForeground(new java.awt.Color(255, 255, 255));
        SSbutton1.setText("Search Student");
        SSbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSbutton1ActionPerformed(evt);
            }
        });
        SSpanel1.add(SSbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 40));

        mainpanel.add(SSpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 190, 100));

        CCpanel1.setBackground(new java.awt.Color(0, 102, 102));
        CCpanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CCpanel1.setForeground(new java.awt.Color(255, 255, 255));
        CCpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CCbutton1.setBackground(new java.awt.Color(0, 102, 102));
        CCbutton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        CCbutton1.setForeground(new java.awt.Color(255, 255, 255));
        CCbutton1.setText("Check Class");
        CCpanel1.add(CCbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 40));

        mainpanel.add(CCpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 190, 100));

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SSbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSbutton1ActionPerformed
        // TODO add your handling code here:
        searchstd ss = new searchstd();
        ss.show();
        dispose();
    }//GEN-LAST:event_SSbutton1ActionPerformed

    private void EpbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EpbuttonActionPerformed
        // TODO add your handling code here:
        editprofile f = new editprofile();
        f.show();
        dispose();
    }//GEN-LAST:event_EpbuttonActionPerformed

    private void MAbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAbuttonActionPerformed
                    // TODO add your handling code here:
                    markatddd mra = new markatddd();
                    mra.show();
                    dispose();
    }//GEN-LAST:event_MAbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CAbutton1;
    private javax.swing.JPanel CApanel1;
    private javax.swing.JButton CCbutton1;
    private javax.swing.JPanel CCpanel1;
    private javax.swing.JButton Epbutton;
    private javax.swing.JPanel Eppanel;
    private javax.swing.JButton MAbutton;
    private javax.swing.JPanel MApanel1;
    private javax.swing.JButton SSbutton1;
    private javax.swing.JPanel SSpanel1;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables

    private void searchstd() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
   
}
