
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author COMPUTER CORNER
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginpanel = new javax.swing.JPanel();
        userbutton = new javax.swing.JButton();
        usernamet = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        passwordpanel2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginpanel.setBackground(new java.awt.Color(0, 153, 153));
        loginpanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                loginpanelAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        loginpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userbutton.setBackground(new java.awt.Color(0, 153, 153));
        userbutton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        userbutton.setText("User Name");
        loginpanel.add(userbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        loginpanel.add(usernamet, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 160, -1));

        login.setBackground(new java.awt.Color(0, 153, 153));
        login.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        loginpanel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, -1));

        passwordpanel2.setBackground(new java.awt.Color(0, 153, 153));
        passwordpanel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        passwordpanel2.setText("Password");
        loginpanel.add(passwordpanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, -1));
        loginpanel.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, -1));

        getContentPane().add(loginpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginpanelAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_loginpanelAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_loginpanelAncestorMoved

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
       String psd = new String(jPasswordField1.getPassword());
       if(psd.equals("teacher")){
       Dashboard d = new Dashboard();
       d.show();
       dispose();
       }
       else if(psd.equals("admin")){
       adashboard a = new adashboard();
       a.show();
       dispose();
       }
       else if(psd.equals("parent")){
       Pdashboard p = new Pdashboard();
       p.show();
       dispose();
       }
       else if(psd.equals("student")){
       sdashboard sd = new sdashboard();
       sd.show();
       dispose();
       }
       else
           JOptionPane.showMessageDialog(rootPane, "Worng Password");
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton login;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JButton passwordpanel2;
    private javax.swing.JButton userbutton;
    private javax.swing.JTextField usernamet;
    // End of variables declaration//GEN-END:variables
}
